### PR TITLE
Added highlights from ES to the results table

### PR DESCRIPTION
**Pull request by wongband**

### CODE REVIEW

**Review by srkirkland — CHANGES_REQUESTED** [review]
try again without changing all of the formatting.  Also I don't think you handled the case when searching by room or namNumber.

**Comment by wongband** [comment]
These pushes ^^^^^ would fix what you addressed in your comment @srkirkland

**Review by srkirkland — COMMENTED** [review]
Ok the highlight works well but has an issue if the search term matches more than one field.  i.e. searching for mrak 15

2:10
it will only highlight part of the match.  Also I don’t know the best way to do it but i am imagining a nice function which can take the highlight object for the current row and decide what to show in the cell, given the column name.  that way if we do add highlights later (like to NAM) then it would work as well.  That part might not be worth it, I’ll leave that up to you as to if you want to attempt that
2:11
but otherwise I think it looks good except for the multiple highlight issue.  I think you just need to change your logic to check independently for each column what the highlight should be (for building/room at least) instead of a if/else

**Review by srkirkland — APPROVED** [review]
i think this will do the trick for now.  In the future I might have you update it so that we match more fields (like namNumber maybe) but for now 👍  🚢

**Pull request merged**
